### ISSUE TITLE
Unsafe use of getClass().getResource()

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/log-viewer#60]
Uses: https://github.com/search?q=repo%3Aqupath%2Flog-viewer+getClass%28%29.getResource%28&type=code

This may or may not be a problem for the time being; I only ran into issues when subclassing (the subclass was looking for resources in its own resource directory).

See: https://codeql.github.com/codeql-query-help/java/java-unsafe-get-resource/

**Comment by Rylern** [comment]
Thanks, I'm also going to correct this in the OMERO extension
